// db/seed.js — populates SQLite with 17 client profiles and the AI solutions catalog.
// Idempotent: safe to re-run; uses INSERT OR REPLACE.
const db = require('./schema');
const aiCatalog = require('./ai_catalog');

// ---- AI Solutions Catalog (master menu) ----
const insertCatalog = db.prepare(`
  INSERT OR REPLACE INTO ai_solutions_catalog (name, category, description, industries, est_value)
  VALUES (?, ?, ?, ?, ?)
`);
const tx = db.transaction((rows) => {
  for (const r of rows) {
    insertCatalog.run(r.name, r.category, r.description, JSON.stringify(r.industries), r.est_value || '');
  }
});
tx(aiCatalog);

// ---- Helper to make a solution match record ----
const sol = (name, why, est) => ({ name, why, est_value: est });

// ---- Client profiles ----
// Each entry is designed to:
//  - classify the sector/industry/sub_industry
//  - capture 3-5 pain points that AI can actually address
//  - suggest 3-5 specific AI solutions with WHY they match and estimated value
const clients = [
  {
    name: 'Teddy Sibuyi',
    title: 'Financial Planner',
    company: '',
    website: '',
    sector: 'Finance',
    industry: 'Financial Advisory',
    sub_industry: 'Personal Financial Planning',
    bio: 'Financial Planner helping individuals and families build, protect, and transfer wealth through structured financial plans.',
    focus_areas: ['Retirement planning', 'Investment planning', 'Tax-efficient structuring', 'Risk cover', 'Estate planning'],
    pain_points: [
      'Repetitive fact-find and plan-drafting for every new client',
      'Time spent on KYC/AML and compliance documentation',
      'Low-frequency client touchpoints — clients disengage between annual reviews',
      'Difficulty scaling personalized advice without hiring more advisors',
      'Market and regulatory changes require constant re-research',
    ],
    ai_solutions: [
      sol('AI Document Intelligence', 'Auto-extract ID, payslip, bank statements from client uploads into your fact-find template.', 'ZAR 30k setup + ZAR 3k/mo'),
      sol('AI Report Drafter', 'Draft a 70% complete financial plan from a 30-min fact-find transcript.', 'ZAR 25k setup + ZAR 2k/mo'),
      sol('AI Customer Support Bot', '24/7 WhatsApp bot answering "what does my policy cover?" without you picking up the phone.', 'ZAR 18k setup + ZAR 1.5k/mo'),
      sol('Predictive Risk Scoring', 'Flag clients at risk of lapsing or under-insured before it happens.', 'ZAR 40k pilot'),
    ],
    tags: ['finance', 'advisory', 'wealth', 'individual-clients'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Seth Ratshitanga',
    title: 'Private & Personal Banking Specialist',
    company: '',
    website: '',
    sector: 'Banking',
    industry: 'Banking & Lending',
    sub_industry: 'Commercial & Residential Financing',
    bio: 'Private and personal banking specialist with deep expertise in commercial and residential finance — home loans, commercial property finance, asset finance.',
    focus_areas: ['Home loans', 'Commercial property finance', 'Asset finance', 'Bond applications', 'Customer relationship management'],
    pain_points: [
      'Manual collection and verification of client documents (payslips, bank statements, financials)',
      'Long turnaround times losing deals to faster competitors',
      'Re-keying data from applications into multiple bank systems',
      'Difficulty pre-qualifying leads from social media and referrals',
      'Compliance/FAIS obligations require auditable trails',
    ],
    ai_solutions: [
      sol('AI Document Intelligence', 'OCR + classify payslips, bank statements, CIPC docs in seconds; auto-flag missing items.', 'ZAR 60k setup + ZAR 5k/mo'),
      sol('AI Sales / Lead-Qual Bot', 'WhatsApp bot that pre-qualifies a lead and books the appointment with you — only serious leads arrive.', 'ZAR 20k setup + ZAR 1.5k/mo'),
      sol('Predictive Risk Scoring', 'Pre-screen credit profile against bank criteria before submission — higher approval rates, faster.', 'ZAR 80k pilot'),
      sol('AI Customer Support Bot', 'After-hours bot that updates clients on application status — frees you from "any update?" calls.', 'ZAR 18k setup + ZAR 1.5k/mo'),
    ],
    tags: ['banking', 'lending', 'financing', 'high-ticket'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Tsietsi Molai',
    title: 'Transaction Advisor',
    company: '',
    website: '',
    sector: 'Finance',
    industry: 'Corporate Finance / Advisory',
    sub_industry: 'M&A, MBO, LBO, BEE, Capital Raising',
    bio: 'Transaction advisor covering the full deal spectrum: M&A, MBOs, LBOs, BEE structuring, financial modelling, due diligence, capital raising, purchase order funding, and invoice discounting.',
    focus_areas: ['Mergers & Acquisitions', 'MBO / LBO structuring', 'BEE transactions', 'Financial modelling', 'Due Diligence', 'Capital raising', 'PO funding', 'Invoice discounting'],
    pain_points: [
      'Reading 200-page CIMs/dataroom docs late at night',
      'Rebuilding financial models from scratch for every pitch',
      'Repetitive DD checklists that eat associate hours',
      'BEE certificate & ownership verification is slow and manual',
      'Limited time for business development vs. deal execution',
    ],
    ai_solutions: [
      sol('AI Document Intelligence', 'Q&A over CIMs/datarooms — ask "what is the recurring revenue?" and get a sourced answer in seconds.', 'ZAR 80k setup + ZAR 6k/mo'),
      sol('AI Report Drafter', 'Generate first-draft financial models and IC memos from raw deal data + your templates.', 'ZAR 120k setup + ZAR 8k/mo'),
      sol('Process / Workflow Automation', 'Automate the DD checklist: request, chase, receive, log, escalate — paper trail included.', 'ZAR 60k pilot'),
      sol('AI Customer Support Bot', 'White-label deal pipeline bot for your portfolio companies and introducers.', 'ZAR 30k setup'),
    ],
    tags: ['finance', 'advisory', 'deals', 'high-value', 'enterprise'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Zanele Masuku',
    title: 'Diagnostic Radiographer (Cathlab & Theatre) | Licensed Gas Installer',
    company: 'Gas Installations (Residential)',
    website: '',
    sector: 'Healthcare',
    industry: 'Medical Imaging',
    sub_industry: 'Cathlab & Theatre Radiography',
    bio: 'Diagnostic radiographer specialising in Cathlab (cardiology) and Theatre radiography across orthopaedic, urology, vascular, and neurosurgery. Also runs a licensed residential gas installation business (heaters, stoves, fireplaces).',
    focus_areas: ['Cathlab imaging (cardiology)', 'Theatre radiography — orthopaedic, urology, vascular, neurosurgery', 'Gas product installation (residential only)'],
    pain_points: [
      'Time-consuming image post-processing and reporting',
      'Manual scheduling across multiple theatre lists',
      'Sourcing warm referrals to surgeons (she literally says "TELL YOUR SURGEON FRIENDS!")',
      'Gas install business: quote generation, booking, after-install follow-up all on WhatsApp',
      'Compliance documentation for both medical and gas (PIRBs, SANS, HPCSA)',
    ],
    ai_solutions: [
      sol('Medical Imaging AI', 'Cathlab/theatre triage + second-read assistance for high-volume cases; auto-draft structured report from DICOM series.', 'ZAR 150k pilot + ZAR 12k/mo'),
      sol('AI Report Drafter', 'Pre-fill radiology reports from prior templates + current scan — saves 20-30 min per case.', 'ZAR 40k setup'),
      sol('AI Sales / Lead-Qual Bot', 'WhatsApp bot for gas installations: takes address, photos, gas type, sends quote + books slot.', 'ZAR 15k setup + ZAR 1k/mo'),
      sol('AI Customer Support Bot', 'After-install follow-up + COC certificate copy on demand.', 'ZAR 12k setup'),
    ],
    tags: ['healthcare', 'radiology', 'energy', 'residential', 'dual-business'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Tsediso Nthakhe',
    title: 'Certified Ethical Hacker | Penetration Tester | DevOps Engineer',
    company: '',
    website: '',
    sector: 'Cybersecurity',
    industry: 'Cybersecurity & DevOps',
    sub_industry: 'Application Security & Cloud Engineering',
    bio: 'Certified Ethical Hacker working as a penetration tester at a private firm and full-time DevOps engineer. Engaged by major banks and telecoms to put out application security fires.',
    focus_areas: ['Penetration testing', 'Application security', 'DevSecOps', 'Cloud security', 'Incident response'],
    pain_points: [
      'Sifting through thousands of SAST/DAST findings — most are noise',
      'Pen-test report writing eats weekends',
      'Repeatable security runbooks that no one updates',
      'Knowledge transfer between engagements — every client is a re-onboard',
      'Bridging dev velocity and security gates in CI/CD',
    ],
    ai_solutions: [
      sol('AI Vulnerability Triage', 'Cluster, dedupe, and prioritise vulns; auto-draft a prioritised backlog for the dev team.', 'ZAR 80k setup + ZAR 6k/mo'),
      sol('AI Report Drafter', 'Turn pen-test notes + screenshots into a fully formatted client report with executive summary.', 'ZAR 60k setup + ZAR 2k/mo'),
      sol('AI Code Review & DevOps Copilot', 'In-PR security review + fix suggestions — embed directly in their GitHub/GitLab.', 'ZAR 50k setup + ZAR 5k/mo'),
      sol('Internal Knowledge Copilot', 'Private copilot trained on past reports, your methodology, and client-specific patterns.', 'ZAR 70k setup + ZAR 4k/mo'),
      sol('AIOps / Log Intelligence', 'Cluster alerts across the SOC stack and predict incident clusters before they fire.', 'ZAR 100k pilot'),
    ],
    tags: ['cybersecurity', 'devops', 'banking', 'telecoms', 'high-ticket', 'strategic'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Buli Ngcobo',
    title: 'HR & Labour Specialist',
    company: 'HR & Labour Advisory Firm',
    website: '',
    sector: 'HR Services',
    industry: 'HR & Labour Advisory',
    sub_industry: 'Consulting — SMEs & Corporates',
    bio: 'Runs an HR & Labour advisory consulting firm supporting various types of businesses with HR policy, CCMA representation, and labour compliance.',
    focus_areas: ['HR policy drafting', 'CCMA representation', 'Labour compliance audits', 'Disciplinary processes', 'Training'],
    pain_points: [
      'Drafting the same 12 HR policies for every new client',
      'High volume of basic employee queries (leave balance, UIF, payslips)',
      'CCMA bundle preparation is a 30-hour manual job',
      'Keeping up with BCEA, LRA, EEA amendments and case law',
      'Inconsistent advice across consultants in the firm',
    ],
    ai_solutions: [
      sol('AI Document Intelligence', 'One-shot generation of all 12+ HR policies tailored to client industry and headcount.', 'ZAR 35k setup'),
      sol('AI Report Drafter', 'Pre-draft CCMA bundles: chronology, evidence index, argument outline.', 'ZAR 60k setup + ZAR 2k/mo'),
      sol('AI Customer Support Bot', 'White-label employee self-service bot for your clients — leave balance, payslip, FAQs.', 'ZAR 25k per client deployment'),
      sol('Internal Knowledge Copilot', 'Copilot trained on your firm’s precedents + SA labour law updates.', 'ZAR 70k setup + ZAR 4k/mo'),
    ],
    tags: ['hr', 'labour', 'compliance', 'recurring-revenue'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Edwin Mokami',
    title: 'IT Consultant | DevOps, Software Dev, Cloud',
    company: 'Newvation Solutions',
    website: 'www.newvation.co.za',
    sector: 'IT Services',
    industry: 'Cloud & Software Engineering',
    sub_industry: 'DevOps, Cloud Engineering, Software Development',
    bio: 'Founder of Newvation Solutions, an IT consulting firm delivering DevOps, software development, and cloud engineering services to clients in banking, insurance, and other global organisations.',
    focus_areas: ['DevOps & SRE', 'Cloud engineering (AWS/Azure/GCP)', 'Software development', 'Banking & insurance clients', 'Global delivery'],
    pain_points: [
      'CI/CD pipelines that grow unmaintainable across clients',
      'Cloud cost surprises on client bills',
      'Knowledge transfer between engineers on client engagements',
      'Proposals and SoWs drafted from scratch each time',
      'Client wanting "AI" features bolted on without a strategy',
    ],
    ai_solutions: [
      sol('AI Code Review & DevOps Copilot', 'Embed AI code review + runbook automation across your client engagements.', 'ZAR 60k setup + ZAR 5k/mo per team'),
      sol('AIOps / Log Intelligence', 'Predictive incident clustering for client platforms you manage.', 'ZAR 90k pilot'),
      sol('AI Document Intelligence', 'Spin up a new client environment in days, not weeks: read their RFP/RFI and auto-propose architecture.', 'ZAR 80k setup + ZAR 5k/mo'),
      sol('AI Report Drafter', 'First-draft SoWs, architecture decision records, and post-implementation reports from your notes.', 'ZAR 40k setup + ZAR 2k/mo'),
      sol('Internal Knowledge Copilot', 'RAG over your past client engagements — junior engineers ramp 2x faster.', 'ZAR 70k setup + ZAR 4k/mo'),
    ],
    tags: ['it-services', 'devops', 'cloud', 'banking', 'insurance', 'global', 'partner-potential'],
    contact_email: '',
    contact_phone: '',
    website: 'www.newvation.co.za',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Tsebo Koena',
    title: 'Consulting Engineer (Civil) | Project Manager | Business Developer',
    company: '',
    website: '',
    sector: 'Construction',
    industry: 'Civil Engineering',
    sub_industry: 'Consulting, Project Management, Business Development',
    bio: 'Civil consulting engineer and project manager with a strong commercial / business-development bent — sits at the intersection of technical delivery and winning work.',
    focus_areas: ['Civil engineering consulting', 'Project management', 'Business development', 'Tender responses', 'Stakeholder management'],
    pain_points: [
      'Tender response cycles that consume BD and engineering time simultaneously',
      'Reusing past bid content is messy and inconsistent',
      'BoQ extraction from drawings is slow',
      'Weekly progress reports for multiple stakeholders are repetitive',
      'Site progress photos pile up unanalysed',
    ],
    ai_solutions: [
      sol('AI Proposal & Bid Writer', 'Cut tender response time 40-60% with an AI trained on your past winning bids + technical library.', 'ZAR 80k setup + ZAR 5k/mo'),
      sol('AI Document Intelligence', 'Auto-extract BoQs from drawings and spec sheets into Excel.', 'ZAR 60k setup + ZAR 3k/mo'),
      sol('Computer Vision Inspection', 'Weekly site-photo analysis: progress %, PPE compliance, snag-list auto-generation.', 'ZAR 70k pilot + ZAR 4k/mo'),
      sol('AI Report Drafter', 'Generate weekly progress reports from site notes + photos + schedule.', 'ZAR 35k setup + ZAR 2k/mo'),
    ],
    tags: ['construction', 'civil', 'tendering', 'bd'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Sizwe Mdluli',
    title: 'M&E Engineering Works Contractor | Consulting Project Manager',
    company: '',
    website: '',
    sector: 'Construction',
    industry: 'Mechanical & Electrical Engineering',
    sub_industry: 'M&E Contracting & Project Management',
    bio: 'Mechanical and electrical engineering works contractor and consulting project manager — delivers M&E scope and runs projects for building-services clients.',
    focus_areas: ['M&E contracting', 'Building services', 'Project management', 'Energy audits', 'Compliance documentation'],
    pain_points: [
      'Equipment spec comparison across vendors is manual',
      'Energy audit reports take weeks of data crunching',
      'BoQs and variation orders are labour-intensive',
      'Safety and incident reporting eats the safety officer’s time',
      'Multiple concurrent projects strain reporting capacity',
    ],
    ai_solutions: [
      sol('AI Document Intelligence', 'Spec sheet Q&A: "find all LV switchgear rated ≥ 4000A in our preferred-vendor list."', 'ZAR 60k setup + ZAR 3k/mo'),
      sol('AI Report Drafter', 'Auto-draft energy audit reports from meter data + baseline templates.', 'ZAR 50k setup + ZAR 3k/mo'),
      sol('AI Proposal & Bid Writer', 'Tender responses that pull from your last 3 years of M&E bids.', 'ZAR 70k setup + ZAR 4k/mo'),
      sol('AI Customer Support Bot', 'WhatsApp bot for site queries, vendor onboarding, and client updates.', 'ZAR 18k setup + ZAR 1.5k/mo'),
    ],
    tags: ['construction', 'mechanical', 'electrical', 'project-management'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Ukwimi Sakala',
    title: 'Business Assurance Manager — Revenue & Fraud, Process Automation',
    company: '',
    website: '',
    sector: 'Telecommunications',
    industry: 'Risk, Assurance & Process Automation',
    sub_industry: 'Revenue Assurance & Fraud Risk',
    bio: 'Business Assurance Manager with 9 years of telecoms experience focused on revenue and fraud management risks and process automation.',
    focus_areas: ['Revenue assurance', 'Fraud risk management', 'Process automation', 'Control testing', 'Telecoms BSS/OSS'],
    pain_points: [
      'Pattern detection across millions of CDRs is impossible manually',
      'Revenue leakage sources are numerous (rating, mediation, billing, interconnect)',
      'Control testing is repetitive and people-dependent',
      'Manual assurance workflows don’t scale with product launches',
      'Fraud patterns evolve faster than rule engines',
    ],
    ai_solutions: [
      sol('Revenue Assurance AI', 'Anomaly detection on CDR / billing data — find leakage and under-rating automatically.', 'ZAR 250k pilot + ZAR 25k/mo'),
      sol('Predictive Risk Scoring', 'Fraud scoring on transactions / SIM swaps / device changes in real time.', 'ZAR 200k pilot + ZAR 20k/mo'),
      sol('Process / Workflow Automation', 'End-to-end automation of control tests with auto-evidence and exception routing.', 'ZAR 120k setup + ZAR 8k/mo'),
      sol('Compliance & Control Testing', 'Auto-evidence pack generation for audit and regulator submissions.', 'ZAR 100k setup + ZAR 6k/mo'),
      sol('AIOps / Log Intelligence', 'Correlate assurance signals with network/ops logs to find root cause faster.', 'ZAR 90k pilot'),
    ],
    tags: ['telecoms', 'risk', 'fraud', 'revenue-assurance', 'enterprise', 'high-value'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Nkululeko Kunene',
    title: 'Independent Financial Advisor (Wealth, Estate, Risk)',
    company: '',
    website: '',
    sector: 'Finance',
    industry: 'Financial Advisory & Insurance',
    sub_industry: 'Wealth, Estate, Short & Long-term Risk',
    bio: 'Independent financial advisor running own practice, focused on wealth creation, estate planning, and long/short-term risk cover.',
    focus_areas: ['Wealth creation', 'Estate planning', 'Long-term insurance', 'Short-term insurance', 'Retirement annuities'],
    pain_points: [
      'Client fact-finds are long and inconsistent',
      'Comparing policies across insurers is slow',
      'Estate plan drafting is bespoke and expensive to scale',
      'Lead nurturing is hit-or-miss between initial contact and policy issue',
      'Compliance (FAIS / POPI / FICA) is heavy',
    ],
    ai_solutions: [
      sol('AI Document Intelligence', 'Capture and structure fact-finds from WhatsApp voice notes + uploaded docs.', 'ZAR 30k setup + ZAR 2k/mo'),
      sol('AI Report Drafter', 'Generate first-draft estate plans and investment proposals from a fact-find.', 'ZAR 40k setup + ZAR 2k/mo'),
      sol('AI Customer Support Bot', '24/7 lead-nurture + policy-status WhatsApp bot.', 'ZAR 18k setup + ZAR 1.5k/mo'),
      sol('Predictive Risk Scoring', 'Identify which leads are most likely to convert and which clients are at lapse risk.', 'ZAR 50k pilot'),
    ],
    tags: ['finance', 'advisory', 'insurance', 'wealth', 'estate'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Lefa Biya',
    title: 'Multimedia Specialist (Web, Graphic Design, Photography)',
    company: '',
    website: '',
    sector: 'Creative',
    industry: 'Multimedia & Design',
    sub_industry: 'Web, Graphic Design, Corporate & Personal Photography',
    bio: 'Multimedia specialist offering web design, graphic design, and corporate and personal-event photography.',
    focus_areas: ['Web design', 'Graphic design', 'Corporate photography', 'Personal events photography', 'Brand identity'],
    pain_points: [
      'Editing and culling hundreds of event photos is hours of work',
      'Multiple revision cycles with clients',
      'SMM-style deliverables take time away from design work',
      'Proposals and scopes written from scratch',
      'Asset library becomes unsearchable as it grows',
    ],
    ai_solutions: [
      sol('AI Photo Enhancement & Curation', 'Auto-cull, auto-enhance, auto-tag event photos — pre-delivery in 20% of the time.', 'ZAR 25k setup + ZAR 1.5k/mo'),
      sol('AI Design Assistant', 'Generate moodboards and design variants from a brief, for client review.', 'ZAR 35k setup + ZAR 2k/mo'),
      sol('AI Marketing Content Engine', 'Auto-generate captions, social posts, and blog copy from photo sets.', 'ZAR 20k setup + ZAR 1.5k/mo'),
      sol('AI Customer Support Bot', 'Lead-qual + booking bot for corporate and personal shoots.', 'ZAR 15k setup + ZAR 1k/mo'),
    ],
    tags: ['creative', 'photography', 'design', 'web', 'smm'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Tiyani Phaweni',
    title: 'Executive Director',
    company: 'Little Swift / Robot Creative / Tom',
    website: 'www.little-swift.co.za',
    sector: 'Creative / Tech',
    industry: 'Creative Agencies & Product',
    sub_industry: 'Multiple (check sites for details)',
    bio: 'Executive Director across multiple ventures: little-swift.co.za, robotcreative.co.za, tom.little-swift.co.za.',
    focus_areas: ['Creative direction', 'Product / venture leadership', 'Brand strategy', 'Multi-business ops'],
    pain_points: [
      'Coordinating multiple brands with different audiences',
      'Content production capacity vs. multiple brand calendars',
      'Client onboarding & proposal turnaround',
      'Cross-brand reporting and visibility for the exec seat',
    ],
    ai_solutions: [
      sol('AI Marketing Content Engine', 'Multi-brand content engine: same AI, different brand voices.', 'ZAR 50k setup + ZAR 4k/mo'),
      sol('AI Brand & Onboarding Assistant', 'Client onboarding flows + intake + project scoping for the agency side.', 'ZAR 30k setup'),
      sol('AI Report Drafter', 'Monthly brand health + project status reports for the executive chair.', 'ZAR 35k setup + ZAR 2k/mo'),
      sol('Internal Knowledge Copilot', 'Cross-brand RAG so any team member can ask "what did we do for X client last year?"', 'ZAR 60k setup + ZAR 4k/mo'),
    ],
    tags: ['creative', 'agency', 'multi-brand', 'executive'],
    contact_email: '',
    contact_phone: '',
    website: 'www.little-swift.co.za',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Nkululeko Mpambo',
    title: 'Commercial Sales & Rentals (Real Estate) | Auctioneer | Legal Services',
    company: '',
    website: '',
    sector: 'Real Estate',
    industry: 'Real Estate & Legal Services',
    sub_industry: 'Commercial Property, Auctioneering, Legal',
    bio: 'Commercial real estate agent focused on sales and rentals, working auctioneer, and provider of legal services within property transactions.',
    focus_areas: ['Commercial property sales', 'Commercial rentals', 'Auctioneering', 'Conveyancing & legal', 'Lease & sale agreements'],
    pain_points: [
      'Property listing copy written one-by-one for each portal',
      'Buyer/tenant qualification is manual and time-wasting',
      'Lease & sale agreement drafting is repetitive',
      'Auction catalogues and bidder packs are heavy manual jobs',
      'Inquiries on WhatsApp at all hours',
    ],
    ai_solutions: [
      sol('AI Marketing Content Engine', 'Generate listing descriptions, social posts, and ad copy from a property spec sheet — multiple portals at once.', 'ZAR 30k setup + ZAR 2k/mo'),
      sol('AI Sales / Lead-Qual Bot', '24/7 WhatsApp bot that qualifies buyers/tenants and books viewings.', 'ZAR 18k setup + ZAR 1.5k/mo'),
      sol('AI Document Intelligence', 'Generate first-draft lease, sale, and auction documents from your templates.', 'ZAR 60k setup + ZAR 3k/mo'),
      sol('AI Report Drafter', 'Auction catalogue + bidder pack generation in hours, not days.', 'ZAR 40k setup'),
    ],
    tags: ['real-estate', 'legal', 'auctioneering', 'commercial'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Isaac Mlangeni',
    title: 'CA(SA) | Accounting, Advisory & Consulting',
    company: '',
    website: '',
    sector: 'Finance',
    industry: 'Accounting & Advisory',
    sub_industry: 'CA(SA) Practice — Audit, Tax, Advisory',
    bio: 'Chartered Accountant (SA) running an accounting, advisory, and consulting firm — full spectrum from compliance to advisory.',
    focus_areas: ['Audit & assurance', 'Tax compliance & advisory', 'IFRS reporting', 'Bookkeeping & accounting', 'Business advisory'],
    pain_points: [
      'Bookkeeping review is repetitive and time-bound to month-end',
      'Audit working papers are manually assembled',
      'SARS updates and practice notes change frequently',
      'Client queries on tax/IFRS eat senior time',
      'Advisory engagements need fresh market data, fast',
    ],
    ai_solutions: [
      sol('AI Document Intelligence', 'Auto-extract trial balances, invoices, bank lines into structured review workbooks.', 'ZAR 70k setup + ZAR 4k/mo'),
      sol('AI Report Drafter', 'Pre-draft tax computations, management accounts, and audit reports from source data.', 'ZAR 60k setup + ZAR 3k/mo'),
      sol('Internal Knowledge Copilot', 'RAG over SARS practice notes + IFRS updates + your own firm’s precedents.', 'ZAR 70k setup + ZAR 4k/mo'),
      sol('AI Customer Support Bot', 'Client-facing bot for "what do I need for VAT201?" style questions — reduces emails.', 'ZAR 18k setup + ZAR 1.5k/mo'),
      sol('Forecasting & Scenario Modelling', 'Quick cash-flow & scenario forecasts for SME advisory engagements.', 'ZAR 50k pilot'),
    ],
    tags: ['accounting', 'audit', 'tax', 'ca', 'advisory', 'enterprise'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'Ungwang Boiteto',
    title: 'Professional Architect (Uks)',
    company: '',
    website: '',
    sector: 'Architecture',
    industry: 'Architecture & Interior Design',
    sub_industry: 'SLP, Industrial, Community, Multi-residential, Commercial',
    bio: 'Professional architect running an architecture & interior design firm working on student living, industrial, community, multi-residential, and commercial projects.',
    focus_areas: ['Architecture', 'Interior design', 'Student living projects', 'Industrial buildings', 'Community facilities', 'Multi-residential', 'Commercial'],
    pain_points: [
      'Design iterations consume junior architect hours',
      'Code/regulation compliance checks are manual',
      'Client visualisation delays sign-off',
      'Spec & BOQ writing is repetitive',
      'Photo-realistic renders cost time and money',
    ],
    ai_solutions: [
      sol('AI Design Assistant', 'Generate concept renders and layout variants from a brief — faster client sign-off.', 'ZAR 50k setup + ZAR 3k/mo'),
      sol('AI Document Intelligence', 'Auto-check plans against SANS / building code / town planning rules.', 'ZAR 90k pilot + ZAR 5k/mo'),
      sol('AI Report Drafter', 'Generate specifications, BOQs, and project manuals from your templates + drawings.', 'ZAR 60k setup + ZAR 3k/mo'),
      sol('AI Customer Support Bot', 'Client portal bot for project updates, document requests, and meeting booking.', 'ZAR 18k setup + ZAR 1.5k/mo'),
    ],
    tags: ['architecture', 'interior', 'construction', 'design', 'multi-sector'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },

  {
    name: 'BaileB',
    title: 'Fashion Designer | Social Media Manager | Marketing & Events Specialist',
    company: '',
    website: '',
    sector: 'Fashion & Marketing',
    industry: 'Fashion Design & Marketing',
    sub_industry: 'Apparel, SMM, Marketing, Events',
    bio: 'Fashion designer, social media manager, and marketing/communications/events specialist. Passion project: classic golf apparel sold for ambience and personal brand.',
    focus_areas: ['Fashion design (classic & golf apparel)', 'Social media management', 'Marketing & communications', 'Events specialist'],
    pain_points: [
      'Design-to-production cycle is slow and dependent on sampling',
      'Social content production for multiple clients is bandwidth-limited',
      'Event logistics and run-of-show consume evenings',
      'E-commerce product descriptions written one by one',
      'Brand presence consistency across channels',
    ],
    ai_solutions: [
      sol('AI Design Assistant', 'Generate fashion sketches, moodboards, and pattern variations from a brief.', 'ZAR 30k setup + ZAR 2k/mo'),
      sol('AI Marketing Content Engine', 'Multi-client content engine: captions, reels scripts, ad copy.', 'ZAR 30k setup + ZAR 2k/mo'),
      sol('AI Photo Enhancement & Curation', 'Auto-enhance and tag lookbook / product photography.', 'ZAR 20k setup + ZAR 1k/mo'),
      sol('AI Report Drafter', 'Event run-of-show, supplier briefs, and post-event reports from notes.', 'ZAR 25k setup + ZAR 1k/mo'),
    ],
    tags: ['fashion', 'marketing', 'events', 'smm', 'creative'],
    contact_email: '',
    contact_phone: '',
    intro_status: 'Not contacted',
    source: 'Business Network Group',
  },
];

// ---- Insert or update clients ----
// Add a UNIQUE index on name for ON CONFLICT to work (must exist before prepare)
db.exec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_clients_name_unique ON clients(name)`);

const upsert = db.prepare(`
  INSERT INTO clients (name, title, company, website, sector, industry, sub_industry, bio,
    focus_areas, pain_points, ai_solutions, tags, contact_email, contact_phone,
    intro_status, source, region)
  VALUES (@name, @title, @company, @website, @sector, @industry, @sub_industry, @bio,
    @focus_areas, @pain_points, @ai_solutions, @tags, @contact_email, @contact_phone,
    @intro_status, @source, @region)
  ON CONFLICT(name) DO UPDATE SET
    title=excluded.title, company=excluded.company, website=excluded.website,
    sector=excluded.sector, industry=excluded.industry, sub_industry=excluded.sub_industry,
    bio=excluded.bio, focus_areas=excluded.focus_areas, pain_points=excluded.pain_points,
    ai_solutions=excluded.ai_solutions, tags=excluded.tags,
    contact_email=excluded.contact_email, contact_phone=excluded.contact_phone,
    intro_status=excluded.intro_status, source=excluded.source, updated_at=CURRENT_TIMESTAMP
`);

const tx2 = db.transaction((rows) => {
  for (const c of rows) {
    upsert.run({
      name: c.name,
      title: c.title || '',
      company: c.company || '',
      website: c.website || '',
      sector: c.sector || '',
      industry: c.industry || '',
      sub_industry: c.sub_industry || '',
      bio: c.bio || '',
      focus_areas: JSON.stringify(c.focus_areas || []),
      pain_points: JSON.stringify(c.pain_points || []),
      ai_solutions: JSON.stringify(c.ai_solutions || []),
      tags: JSON.stringify(c.tags || []),
      contact_email: c.contact_email || '',
      contact_phone: c.contact_phone || '',
      intro_status: c.intro_status || 'Not contacted',
      source: c.source || 'Business Network Group',
      region: c.region || 'South Africa',
    });
  }
});
tx2(clients);

console.log(`✅ Seeded ${clients.length} clients and ${aiCatalog.length} AI solutions.`);
console.log(`📂 Database: ${require('path').join(__dirname, '..', 'data', 'ngulubehub.sqlite')}`);
